# Generated by Django 5.0.7 on 2024-08-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_transaction_user_transa_deposit_13ab53_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='user_transa_deposit_d319ec_idx',
        ),
    ]
