# Generated by Django 5.0.7 on 2024-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_transaction_user_transa_deposit_d319ec_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='final_balance',
            field=models.FloatField(default=0),
        ),
    ]
