# Generated by Django 5.0.7 on 2024-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_transaction_user_transa_deposit_22cdfd_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='final_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
